### ISSUE TITLE
Forma: Cargador de Archivos (Import File Loader)

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1172]
![image](https://github.com/solop-develop/frontend-core/assets/20288327/741e7d68-7b56-4870-9bb6-aabaab675562)

- [x] solop-develop/vue-1.0#1225
- [x] solop-develop/vue-1.0#1188
- [x] solop-develop/vue-1.0#1219
- [x] solop-develop/vue-1.0#1220
- [ ] solop-develop/frontend-core#68
- [x] solop-develop/vue-1.0#1223
- [ ] solop-develop/frontend-core#67
- [x] solop-develop/vue-1.0#1224
- [x] solop-develop/vue-1.0#1218
- [x] solop-develop/vue-1.0#1283

**Comment by EdwinBetanc0urt** [comment]
Existen mejoras que podrían hacerse en adempiere para asegurar el correcto funcionamiento de este formulario.
- La gestión de adjuntos/imagenes/archivos en vue solo funciona con un manejador de archivos que se configura a nivel de compañía, sin embargo aunque se configure en `System` nunca consigue el manejador de archivos https://github.com/adempiere/adempiere/blob/develop/base/src/org/spin/util/AttachmentUtil.java#L561

**Comment by EdwinBetanc0urt** [comment]
> Existen mejoras que podrían hacerse en adempiere para asegurar el correcto funcionamiento de este formulario.
> 
>     * La gestión de adjuntos/imagenes/archivos en vue solo funciona con un manejador de archivos que se configura a nivel de compañía, sin embargo aunque se configure en `System` nunca consigue el manejador de archivos https://github.com/adempiere/adempiere/blob/develop/base/src/org/spin/util/AttachmentUtil.java#L561

Esta mejora se subió a adempiere en espera de revisión para mezclar https://github.com/adempiere/adempiere/pull/4177

**Comment by niclopup** [comment]
no se logra adjuntar archivo

![image](https://github.com/solop-develop/frontend-core/assets/31936815/cf67eb63-49a9-43a4-a4fa-c8b5e5aee416)


además no se ve el botón para ir al siguiente paso en la primer pantalla

![image](https://github.com/solop-develop/frontend-core/assets/31936815/215aa9c4-3b55-47bb-95f3-4cae279527aa)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.6.8 y del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/82dd170e-628d-4b07-9597-688f5a3eb958
