### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#54]
- [x] solop-develop/vue-1.0#55 
- [ ] solop-develop/frontend-core#41 
- [x] solop-develop/vue-1.0#57 
- [x] solop-develop/vue-1.0#69
