### ISSUE TITLE
Forma: Asignación de Pagos (Payment Allocation)

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#965]
![Image](https://user-images.githubusercontent.com/20288327/228885407-f02415e2-8de8-47ec-b758-c1ed108d0409.png)

- [x] solop-develop/vue-1.0#2074
- [x] Forma: Asignación de Pagos > Listar Organizaciones de filtro.
- [x] solop-develop/vue-1.0#2036
- [x] solop-develop/frontend-core#128
- [x] #2071
- [x] Forma: Asignación de Pagos > Listar Facturas.
- [x] Forma: Asignación de Pagos > Listar Cargos.
- [x] Forma: Asignación de Pagos > Listar Organizaciones de sobre-escritura de transacción.
- [x] Forma: Asignación de Pagos > Calcular Diferencia.
- [x] Forma: Asignación de Pagos > Procesar.

### BugFIx 

- [x] solop-develop/vue-1.0#1312
- [x] solop-develop/vue-1.0#1313
- [x] solop-develop/vue-1.0#1314
- [x] solop-develop/vue-1.0#1315
- [x] solop-develop/vue-1.0#1371
- [ ] solop-develop/frontend-core#127
- [ ] solop-develop/frontend-core#129
- [x] solop-develop/vue-1.0#2076

**Comment by niclopup** [comment]
La forma que se seleccionan los parametros iniciales no es l mejor. El SDN debería ser obligatorio como la moneda

el SDN debería tener una búsqueda igual como en las ventanas

la fecha debería ser por defecto la del día y siempre debería mostrarse también en la segunda parte ya que se modifica según los documentos q se seleccionen.

**2do paso:**

No es practico ue se muestren de manera vertical la sección de "Pagos" y de "Facturas" ya q tienen más datos a ver en columnas por cada registro que para abjo. es mejor si se definen cada sección de manera horizontal como esta en ZK

![image](https://github.com/solop-develop/frontend-core/assets/31936815/f1f408cc-939b-49a3-bebe-bb456584397e)

En este ejemplo se ve como no se visauliza el total asignado en la primer pantall sino ue tengo que mover el scroll horiz a la derecha para ver el campo, si lo muevo, ya no veo los documentos ue tengo seleccionados.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9dcc3c45-2116-4741-a827-9d6d4ad191ab)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/8a0024b2-8d84-4f42-ae96-bf3882323882)


Pago no se visualiza

en este caso con el SDN Seed. no se visualiza un pgo



Lo cerré y volví  a abrir y no se ven los nombres sino los códigos de los datos  q tenia antes seleccionado

![image](https://github.com/solop-develop/frontend-core/assets/31936815/bad95c84-e0a0-4e14-adb1-a7e75bbdf176)



Diferencia sin seleccionar nada

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b1038c6e-5185-45f8-9fd8-a79d3df8f02c)

Reinicio cache y vuelvo a probar

Se ven ok los campos ahora.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/7317ac4f-91b8-42d6-8ee5-edd176c19950)

No me trae ningún PAGO (Egreso)


![image](https://github.com/solop-develop/frontend-core/assets/31936815/255cab9a-89b0-4eeb-806b-2ab1095c5094)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/bcca7c9e-8b59-4b25-8649-ca991e3b12b3)

Vuelvo a ir para atrás y luego al 2do paso nuyevamente y ahora si lo trae

![image](https://github.com/solop-develop/frontend-core/assets/31936815/4174701f-091e-4ff4-88f1-d241d52f806d)


En las facturas aparecen 2 registros, si se marca el 10000030 por 2000 USD, antes de marcar el check el importe "Aplicado" es de -2000 que es el importe correcto al ser un DxP

![image](https://github.com/solop-develop/frontend-core/assets/31936815/68ac5ffe-6be6-4d37-a2c5-531eb21373e5)

Ahora cuando se selecciona dicho DxP, el importe de "Aplicado" pasa a ser POSITIVO

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b0f14512-36a9-486b-9157-2f8fb295cee1)

Si selecciono el 2do registro, este también pasa a POSTIVO pero de alguna manera la diferencia lo suma como negativo quedando -1000

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5083a9f5-3a57-4660-a7e8-7b55baf1f7f4)

Si se selecciona primero el 2do DxP sucede lo mismo

si se marca luego un PAGO este suma NEGATIVO pero como todo queda negativo no cancela correctamente y entiendo no dejaría hacer la asiganción

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b53ba2db-0423-45e8-8e82-5a476fbb9afb)

En ZK se ve claramente como si bien el signo lo determina si es un DxP/IsSoTrx=N (Negativo) o un DxC/IsSoTrx=Y (Positivo), para hacer la DIFERENCIA entre PAGOS y FACTURAS los considera uno menos el otro, tal vez considerando alguno como con Valor absoluto o algo de eso no se.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/8b360b39-2a9b-407c-b03d-fdd177527d65)

**Comment by elsiosanchez** [comment]
### _**Errores**_
- [x] https://github.com/solop-develop/frontend-core/issues/1169
- [x] https://github.com/solop-develop/frontend-core/issues/1170
- [x] https://github.com/solop-develop/frontend-core/issues/1171

**Comment by niclopup** [comment]
veo los siguientes puntos:

1. Grillas Horizontales: Cuando se marca un registro se queda tan pequeño el espacio de alto de la grilla que sólo se ve 1 registro a la vez.Sería ideal quequede lo más alto posible. dejar bien contra abajo los parámetros y la suma (como está en zk) así utilizamos al máximo el espacio, tanto para Pago/Cobro como para DxP/DxC
2. Las Sumas siguen incorrectas. Seleccione 2 DxP que me sumaba NEGATIVO y cuando marque el PAGO (egreso) le sumó el saldo cuando en realidad deberían cancelarse entre sí. ver como lo aplica ZK

![Errores asignación de Pagos 19 7 23](https://github.com/solop-develop/frontend-core/assets/31936815/552727a7-42d4-4ae0-b3f0-e09e590a0f3a)

**Comment by niclopup** [comment]
Habiendo 3 pagos, sólo se visualiza 1 y no se ve la barra para hacer scroll para abajo en la sección de "Pagos"

Zoom 100%
![image](https://github.com/solop-develop/frontend-core/assets/31936815/80c9860c-fe59-48e9-8af5-2f4be44c75d0)

Zoom 67%
![image](https://github.com/solop-develop/frontend-core/assets/31936815/c1268438-1df5-4cd8-a0a1-d4586e7a5271)

Creo que se podría definir más chicas las líneas de los documentos justamente permitiendo la opción de que se puedan ver como mínimo 5 en cada sección (5 Payments - 5 Invoice). 4 como mínimo

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b1cc9a44-72ce-42fa-b155-f1a0f2bf6a50)

**Organización Obligatoria**

Organización obligatoria pese a que no haya diferencia. En este caso en ZK no pide que vuelvas a definir la organización en cada asignación. Si no hay diferencia no es necesaria por que ya la definiste en el filtro inicial, se debe tomar dicha organización

![image](https://github.com/solop-develop/frontend-core/assets/31936815/52909f5f-ba2d-42b6-a7c7-f73f6c6a4a74)

**Acción**

Se seleccionan un pago y una DxP que suman diferencia 0 pero al hacer click en el check no realiza ninguna acción. No genera asignación alguna pese a que da un resultado como que lo realizó.

**Comment by elsiosanchez** [comment]
- [ ] Zoom 100% (Agregar Scroll) 
- [ ] Reducir Tamaño de las Lineas
- [ ] Definir la Organización
- [ ] Acción (Procesar Asignacion)

**Comment by elsiosanchez** [comment]
- [x] solop-develop/vue-1.0#1312
- [x] solop-develop/vue-1.0#1313
- [x] solop-develop/vue-1.0#1314
- [x] solop-develop/vue-1.0#1315

**Comment by niclopup** [comment]
Se logra generar una asignación correctamente

El único detalle que encontré es un tema con la fecha: 

1. faltaría un Callout (o no se exactamente que es) que en ZK se actualiza automáticamente la Fecha definida según la máxima fecha de los documentos que se vayan seleccionando. ahora no puedo hacer gif para mostrles peromañana les paso.

![Al seleccionar una Factura cambia automáticamente la fecha](https://github.com/solop-develop/frontend-core/assets/31936815/9bdddc78-7c17-4bd7-86a5-5555dc34d258)
![Control fecha automático](https://github.com/solop-develop/frontend-core/assets/31936815/3ce74196-2849-4ad1-92c0-7204b874503b)

2. la fecha que se define por alguna razón al digitarla manualmente, la fecha que se ve se considera el día anterior y no la fecha definida,. por esta razón se debe poner una fecha del día siguiente a la de los documentos y no la fecha del día exacto de los documentos como debería ser

**Comment by EdwinBetanc0urt** [comment]
> Se logra generar una asignación correctamente
> 
> El único detalle que encontré es un tema con la fecha:
> 
>     1. faltaría un Callout (o no se exactamente que es) que en ZK se actualiza automáticamente la Fecha definida según la máxima fecha de los documentos que se vayan seleccionando. ahora no puedo hacer gif para mostrles peromañana les paso.
> 
> 
> ![Al seleccionar una Factura cambia automáticamente la fecha](https://user-images.githubusercontent.com/31936815/261447702-9bdddc78-7c17-4bd7-86a5-5555dc34d258.jpg) ![Control fecha automático](https://user-images.githubusercontent.com/31936815/261447708-3ce74196-2849-4ad1-92c0-7204b874503b.jpg)
> 
>     2. la fecha que se define por alguna razón al digitarla manualmente, la fecha que se ve se considera el día anterior y no la fecha definida,. por esta razón se debe poner una fecha del día siguiente a la de los documentos y no la fecha del día exacto de los documentos como debería ser

Este tema se sigue en el siguiente issue https://github.com/solop-develop/frontend-core/issues/1371

**Comment by niclopup** [comment]
A la espera de corregir solop-develop/vue-1.0#2036

**Comment by niclopup** [comment]
Si te parec esta issue la dejamos como entregada y seguimos en las hijas
